### ISSUE TITLE
Merge Platform and Security-page directive

### ISSUE THREAD

**Issue by jobertabma** [EdOverflow/security-txt#13]
A lot of vendors use their Platform page as their Security page or link to it from their Security page. I'd suggest to keep it simple and remove Platform from the RFC. There could be a few examples for the Security-page directive that show it may link to a platform entry. Thoughts?

**Comment by ryancblack** [comment]
While having a clear security page is a best practice contents and intent are often inconsistent. For this reason I feel an optional, but present, platform field to be useful. See, [14](https://github.com/EdOverflow/security-txt/issues/14) for one example related to clear versioning.

**Comment by EdOverflow** [comment]
Security pages can now be specified using the `Contact:` directive. Please refer to Section 2.3: https://www.ietf.org/id/draft-foudil-securitytxt-00.txt.
