### ISSUE TITLE
Use CWE for vulnerability type directive

### ISSUE THREAD

**Issue by jobertabma** [EdOverflow/security-txt#15]
Having free-format definitions for vulnerability types will result in people using different naming for the same vulnerability types. This makes it harder to consume for computers. I'd propose to use Common Weakness Enumeration (CWE) for this. This would require the file to define a CWE version number and a list of CWE IDs. It could look something like this:

```
Out-of-scope-vuln: CAPEC-103 (clickjacking)
Out-of-scope-vuln: CWE-77 (command injection)
```

Using the parentheses is optional and will be ignored, but adds the ability for humans to interpret the meaning of the CWE without the need to look it up. It could be validated with something like:

```
([CAPEC|CWE]+-\d+)(\s+?\(.*\))?
```

**Comment by EdOverflow** [comment]
Oh, I like this! Since most people already use CWE (on HackerOne for instance :wink:), I will almost certainly add this to the spec.

**Comment by EdOverflow** [comment]
We decided to remove the `In-scope:` option (#16) and therefore saw no need in keeping the `Out-of-scope-vuln:` one too.
