### ISSUE TITLE
Valid values for fields

### ISSUE THREAD

**Issue by bAndie91** [EdOverflow/security-txt#17]
What are the valid values for `Reward`, `Disclosure`?
I mean other fields are pretty unambiguous and even numric part of `Reward` and `Disclosure`, but which keywords can replace `Medium` in `Reward` and `Full` in `Disclosure`?
for example: `Reward: Low-50`, `Disclosure: Partial-7`, `Disclosure: Full-never`.
we need a draft to describe these keywords.

**Comment by EdOverflow** [comment]
Hi @bAndie91,

I am currently working on the RFC for this project and in that document every single value must be described. This repo was more just to get the idea out there and see what people thought. Thank you for creating this issue.

**Comment by EdOverflow** [comment]
See: https://www.ietf.org/id/draft-foudil-securitytxt-00.txt
