### ISSUE TITLE
Consider submitting this to the IETF as a draft RFC

### ISSUE THREAD

**Issue by lachlanhunt** [EdOverflow/security-txt#18]
If you really want this to become a standard, then you should definitely consider submitting this and going through the process of making this an RFC.

And you really should change the readme to say that it's a proposal, not a standard.

**Comment by EdOverflow** [comment]
> If you really want this to become a standard, then you should definitely consider submitting this and going through the process of making this an RFC.

I am actually currently working on the draft: https://github.com/EdOverflow/security-txt/issues/17#issuecomment-323588121. :smiley: 

All issues found in this milestone will be included in the draft: https://github.com/EdOverflow/security-txt/milestone/1

> And you really should change the readme to say that it's a proposal, not a standard.

That is a good point. I could have worded that a bit better. Thank you for creating this issue.

**Comment by EdOverflow** [comment]
Done. https://www.ietf.org/id/draft-foudil-securitytxt-00.txt :slightly_smiling_face:
