### ISSUE TITLE
Add some form of support for encrypting details

### ISSUE THREAD

**Issue by Plazmaz** [EdOverflow/security-txt#22]
It would be awesome if website owners could specify a key, then use an encryption algorithm, say RSA, to encrypt their data. I'd imagine if done right, this could take a while to decrypt, and thus make it difficult for scrapers to abuse this system. 

I think this would resolve some of the concerns people have voiced around getting their contact information spammed (for example, https://www.bleepingcomputer.com/news/security/security-txt-standard-proposed-similar-to-robots-txt/#cid6271).

It would be hard for bots to decrypt a ton of slow-decrypting keys, but easy for someone to decrypt just one. I'm not sure if RSA would be the right algorithm for this or not, there may be a better option.

EDIT: An alternative would be making the key a few rounds of bcrypt on the hostname. This would mean bots would need to know the domain, run the bcrypt, and then decrypt the data using the key for each address.

**Comment by EdOverflow** [comment]
Thank you raising an issue, but I will close this ticket in favour of #22.
