### ISSUE TITLE
Serve from /.well-known/security.txt

### ISSUE THREAD

**Issue by gazoakley** [EdOverflow/security-txt#29]
A lot of metadata files for things similar to security.txt are commonly served from /.well-known/. IANA provide the Well Known URI registry for this purpose:

https://tools.ietf.org/html/rfc5785#section-5.1 
https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml

It might be useful to get an assignment from IANA for serving security.txt

**Comment by EdOverflow** [comment]
Hi @gazoakley,

Thank you for raising an issue. I am closing this in favour of #3. On top of that, the new draft will be published today which places security.txt under /.well-known/.
