### ISSUE TITLE
Add PGP external validations (keybase, keyservers)

### ISSUE THREAD

**Issue by emanuelb** [EdOverflow/security-txt#4]
To have more assurance of accurate/trusted information of the PGP key, adding below fields will be useful:
1. keybase page (for example, search for "Security Team" in keybase)
2. mention the availability of the PGP key on key-servers.

**Comment by EdOverflow** [comment]
This was included in the `Encryption:` directive. Please refer to Section 2.4: https://www.ietf.org/id/draft-foudil-securitytxt-00.txt.
