### ISSUE TITLE
Add Payment methods field

### ISSUE THREAD

**Issue by emanuelb** [EdOverflow/security-txt#5]
BugBounties have different set of possible payments methods, such as:
CryptoCurrencies directly (BTC,LTC,ETH,XMR,etc...)
CryptoCurrencies via exchange account (such as coinbase account)
PayPal
BankTransfers
etc..

Example of bug bounty that have limited set of payment options is F-Secure:
https://www.f-secure.com/en/web/labs_global/vulnerability-reward-program

> Payments are made as **bank transfers within the Single Euro Payments Area (SEPA) or international bank (wire) transfers outside the SEPA. We cannot use checks, cryptocurrencies, or use any other money transfer services.** The payment recipient is responsible for any charges or fees levied on the transfer, and for accessing the funds once transferred. Payments are by default done in Euros (EUR) and any currency conversions are done at the current bank rate.

**Comment by EdOverflow** [comment]
Once again, thank you for the suggestion @emanuelb. I have now added a `Payment-method:` option.
