### ISSUE TITLE
Add test accounts informations

### ISSUE THREAD

**Issue by emanuelb** [EdOverflow/security-txt#9]
Some programs encourage users to use test accounts instead of real accounts, see for example in Facebook:
https://www.facebook.com/whitehat/

> Use test accounts when investigating issues. If you cannot reproduce an issue with a test account, you can use a real account (except for automated testing). Do not interact with other accounts without consent (e.g. do not test against Mark Zuckerberg’s account).

**Comment by EdOverflow** [comment]
This was not included in the [Internet draft](https://www.ietf.org/id/draft-foudil-securitytxt-00.txt), because I decided that security.txt should be used when you have found something and not as a way to encourage security researchers to hunt on the company's platform.
